theme-name: color
polybar-config: /home/USER/.config/i3/polybar/color/config.ini
gtk-theme: Otis
icon-theme: Fluent-purple-dark
cursor-theme: ArcDusk Cursors
wallpaper-path: /usr/share/backgrounds/archlan/color.png