#! /bin/sh

poweroff="  Power Off"
restart="  Restart"
lock="  Lock"
logout="  Log Out"

chosen=$(printf "$poweroff\n$restart\n$lock\n$logout" | rofi -dmenu -i -p -theme $HOME/.config/i3/rofi/config.rasi "Power options")
export SUDO_ASKPASS="$HOME/.config/i3/polybar/scripts/askpass"
case "$chosen" in
	$poweroff) poweroff || sudo -A poweroff ;;
	$restart) reboot || sudo -A reboot ;;
	$lock) sh $HOME/.config/i3/scripts/lock ;;
	$logout) kill -9 -1 ;;
	*) exit 1 ;;
esac
