#! /bin/sh

full="1. Fullscreen"
gui="2. Flameshot GUI"
launcher="3. Interactive Launcher"

chosen=$(printf "$full\n$gui\n$launcher" | rofi -dmenu -i -p -theme $HOME/.config/i3/rofi/config.rasi "Screenshot")
case "$chosen" in
        $full) flameshot full -p ~/Pictures/Screenshots/ -d 40 ;;
        $gui) flameshot gui -p ~/Pictures/Screenshots/ ;;
        $launcher) flameshot launcher ;;
        *) exit 1 ;;
esac
