#!/bin/bash

# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    rofi-wal                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Lanhild <archlan@protonmail.com>           +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/25 13:04:34 by Lanhild           #+#    #+#              #
#    Updated: 2022/01/25 13:04:35 by Lanhild          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# This script is invoked when the user has chosen the theme name. It passes the
# arguments here as ${1}, ${2}, ${3} and ${4} and then applies the changes, to 
# in the end restart the window manager to remove visual artifacts.

CFG="$HOME/.config"
XRES="$HOME/.Xresources.d"
DEFDIR="$CFG/i3/scripts/theme-switch/defaults"
WALDIR="/usr/share/backgrounds/archlan"

## Set Style
set_style () {
	# apply wallpaper with pywal
	wal -i $WALDIR/${1}
	
	# set gtk theme, icons and cursor
	if [[ `pidof xsettingsd` ]]; then
		sed -i -e "s|Net/ThemeName .*|Net/ThemeName \"$2\"|g" ${HOME}/.xsettingsd
		sed -i -e "s|Net/IconThemeName .*|Net/IconThemeName \"$3\"|g" ${HOME}/.xsettingsd
		sed -i -e "s|Gtk/CursorThemeName .*|Gtk/CursorThemeName \"$4\"|g" ${HOME}/.xsettingsd
	else
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=\"$2\"/g" ${HOME}/.gtkrc-2.0
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=\"$3\"/g" ${HOME}/.gtkrc-2.0
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=\"$4\"/g" ${HOME}/.gtkrc-2.0
		
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=$2/g" ${CFG}/gtk-3.0/settings.ini
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$3/g" ${CFG}/gtk-3.0/settings.ini
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=$4/g" ${CFG}/gtk-3.0/settings.ini
	fi

	# Change polybar theme
	${CFG}/i3/polybar/$5/launch.sh

	# Save current theme in config.yaml - Used to restore the theme at machine boot. (under development)
	if [[ `pidof Xorg` ]]; then
		printf "" > ${DEFDIR}/config.yaml
		printf "theme-name: ${5}`\n`
polybar-config: /home/USER/.config/i3/polybar/${5}/config.ini`\n`
gtk-theme: ${2}`\n`
icon-theme: ${3}`\n`
cursor-theme: ${4}`\n`
wallpaper-path: ${WALDIR}/${1}" > ${DEFDIR}/config.yaml
	fi

	# Send notification of what theme has been selected
	if [[ `pidof Xorg` ]]; then
		notify-send "${5} theme applied."
	fi
}

set_style "${1}" "${2}" "${3}" "${4}" "${5}"