#!/usr/bin/env bash

## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

DIR="$HOME/.config/i3"
SRC="$HOME/.config/i3/scripts/theme-switch"
rofi_command="rofi -theme $SRC/themes.rasi"

# Themes
theme_1=" Luna"
theme_2=" Roundy"

# Variable passed to rofi
options="$theme_1\n$theme_2"

chosen="$(echo -e "$options" | $rofi_command -p "Available themes : (2)" -dmenu -selected-row 0)"
case $chosen in
    $theme_1)
        bash ${SRC}/set-theme  'aenami_06.jpg' 'Flat-Remix-GTK-Violet-Dark' 'Fluent-purple-dark' 'Layan Cursors' 'luna'
        ;;
    $theme_2)
        bash ${SRC}/set-theme  'aenami_05.jpg' 'Cloudy-Solid-SoftBlue-Dark' 'Colloid-dark' 'Layan Cursors' 'roundy'
        ;;
esac